version: "3"
services:
  elasticsearch:
    build: .
    expose:
      - "9200"
      - "9300"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
